spring:
  application:
    name: user-account-service
  datasource:
    url: jdbc:mysql://localhost:3306/xodium_users_account_db
    username: tunde
    password: password
  jpa:
    hibernate:
      ddl-auto: update
#Kafka config
  kafka:
    bootstrap-servers: localhost:9092
#As producer
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type: true
server:
  port: 8081

# Eureka Discovery Config
eureka:
  client:
    server-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

#Health monitoring, and actuator config
management:
  endpoints:
    web:
      exposure:
        include: "*"





